// ponytail: single source of truth for Venezuela estados + ciudades and the
// list of countries outside Venezuela. Kept as plain consts so the same map
// feeds the zod schema, the registro form, and the admin review view.

export const VENEZUELA_ESTADOS = [
  'Distrito Capital',
  'Amazonas',
  'Anzoátegui',
  'Apure',
  'Aragua',
  'Barinas',
  'Bolívar',
  'Carabobo',
  'Cojedes',
  'Delta Amacuro',
  'Falcón',
  'Guárico',
  'La Guaira',
  'Lara',
  'Mérida',
  'Miranda',
  'Monagas',
  'Nueva Esparta',
  'Portuguesa',
  'Sucre',
  'Táchira',
  'Trujillo',
  'Yaracuy',
  'Zulia',
  'Dependencias Federales',
] as const

export const ESTADO_CIUDADES: Record<string, readonly string[]> = {
  'Distrito Capital': ['Caracas'],
  Amazonas: ['Puerto Ayacucho'],
  Anzoátegui: ['Barcelona', 'Puerto La Cruz', 'Anaco', 'El Tigre'],
  Apure: ['San Fernando', 'Acarigua', 'Guasdualito'],
  Aragua: ['Maracay', 'La Victoria', 'Cagua', 'Turmero'],
  Barinas: ['Barinas', 'Ciudad Bolívar (Barinas)'],
  Bolívar: [
    'Ciudad Bolívar',
    'Ciudad Guayana',
    'Upata',
    'Puerto Ordaz',
    'San Félix',
  ],
  Carabobo: ['Valencia', 'Naguanagua', 'Puerto Cabello', 'Guacara'],
  Cojedes: ['San Carlos', 'Tinaquillo'],
  'Delta Amacuro': ['Tucupita'],
  Falcón: ['Coro', 'Punto Fijo', 'La Vela de Coro'],
  Guárico: ['San Juan de los Morros', 'Calabozo', 'Valle de la Pascua'],
  'La Guaira': ['La Guaira', 'Catia La Mar', 'Maiquetía'],
  Lara: ['Barquisimeto', 'Cabudare', 'Carora', 'El Tocuyo'],
  Mérida: ['Mérida', 'Ejido', 'Tabay', 'Tovar'],
  Miranda: [
    'Los Teques',
    'San Cristóbal',
    'Guarenas',
    'Guatire',
    'Charallave',
    'Ocumare del Tuy',
    'Santa Teresa del Tuy',
  ],
  Monagas: ['Maturín', 'Carúpano', 'Punta de Mata'],
  'Nueva Esparta': ['La Asunción', 'Porlamar', 'Juan Griego'],
  Portuguesa: ['Guanare', 'Acarigua', 'Biscucuy'],
  Sucre: ['Cumaná', 'Carúpano', 'Güiria'],
  Táchira: ['San Cristóbal', 'Táriba', 'Rubio', 'Colón'],
  Trujillo: ['Trujillo', 'Valera', 'Boconó'],
  Yaracuy: ['San Felipe', 'Yaritagua', 'Chivacoa'],
  Zulia: ['Maracaibo', 'Cabimas', 'Ciudad Ojeda', 'San Francisco'],
  'Dependencias Federales': ['Isla de Margarita', 'Los Roques'],
}

export const PAISES_EXTRANJEROS = [
  'Argentina',
  'Bolivia',
  'Brasil',
  'Canadá',
  'Chile',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Ecuador',
  'El Salvador',
  'Estados Unidos',
  'Guatemala',
  'Honduras',
  'México',
  'Nicaragua',
  'Panamá',
  'Paraguay',
  'Perú',
  'Puerto Rico',
  'República Dominicana',
  'Uruguay',
  'Otro',
] as const

export const VENEZUELA = 'Venezuela' as const

export const PAIS_OPTIONS = [VENEZUELA, ...PAISES_EXTRANJEROS] as const