/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as AcercaDeRouteImport } from './routes/acerca-de'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecursosIndexRouteImport } from './routes/recursos/index'
import { Route as AyudaIndexRouteImport } from './routes/ayuda/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RecursosRespirarRouteImport } from './routes/recursos/respirar'
import { Route as RecursosReaccionesNormalesRouteImport } from './routes/recursos/reacciones-normales'
import { Route as RecursosPrimerosAuxiliosRouteImport } from './routes/recursos/primeros-auxilios'
import { Route as RecursosEnraizamientoRouteImport } from './routes/recursos/enraizamiento'
import { Route as ProfesionalRegistroRouteImport } from './routes/profesional/registro'
import { Route as ProfesionalPanelRouteImport } from './routes/profesional/panel'
import { Route as ProfesionalLoginRouteImport } from './routes/profesional/login'
import { Route as ProfesionalCompletarRouteImport } from './routes/profesional/completar'
import { Route as AyudaProfesionalesIndexRouteImport } from './routes/ayuda/profesionales/index'
import { Route as AyudaProfesionalesIdRouteImport } from './routes/ayuda/profesionales/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const AcercaDeRoute = AcercaDeRouteImport.update({
  id: '/acerca-de',
  path: '/acerca-de',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosIndexRoute = RecursosIndexRouteImport.update({
  id: '/recursos/',
  path: '/recursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaIndexRoute = AyudaIndexRouteImport.update({
  id: '/ayuda/',
  path: '/ayuda/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRespirarRoute = RecursosRespirarRouteImport.update({
  id: '/recursos/respirar',
  path: '/recursos/respirar',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosReaccionesNormalesRoute =
  RecursosReaccionesNormalesRouteImport.update({
    id: '/recursos/reacciones-normales',
    path: '/recursos/reacciones-normales',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecursosPrimerosAuxiliosRoute =
  RecursosPrimerosAuxiliosRouteImport.update({
    id: '/recursos/primeros-auxilios',
    path: '/recursos/primeros-auxilios',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecursosEnraizamientoRoute = RecursosEnraizamientoRouteImport.update({
  id: '/recursos/enraizamiento',
  path: '/recursos/enraizamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalRegistroRoute = ProfesionalRegistroRouteImport.update({
  id: '/profesional/registro',
  path: '/profesional/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalPanelRoute = ProfesionalPanelRouteImport.update({
  id: '/profesional/panel',
  path: '/profesional/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalLoginRoute = ProfesionalLoginRouteImport.update({
  id: '/profesional/login',
  path: '/profesional/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalCompletarRoute = ProfesionalCompletarRouteImport.update({
  id: '/profesional/completar',
  path: '/profesional/completar',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaProfesionalesIndexRoute = AyudaProfesionalesIndexRouteImport.update({
  id: '/ayuda/profesionales/',
  path: '/ayuda/profesionales/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaProfesionalesIdRoute = AyudaProfesionalesIdRouteImport.update({
  id: '/ayuda/profesionales/$id',
  path: '/ayuda/profesionales/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca-de': typeof AcercaDeRoute
  '/cuenta': typeof CuentaRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/profesional/completar': typeof ProfesionalCompletarRoute
  '/profesional/login': typeof ProfesionalLoginRoute
  '/profesional/panel': typeof ProfesionalPanelRoute
  '/profesional/registro': typeof ProfesionalRegistroRoute
  '/recursos/enraizamiento': typeof RecursosEnraizamientoRoute
  '/recursos/primeros-auxilios': typeof RecursosPrimerosAuxiliosRoute
  '/recursos/reacciones-normales': typeof RecursosReaccionesNormalesRoute
  '/recursos/respirar': typeof RecursosRespirarRoute
  '/admin/': typeof AdminIndexRoute
  '/ayuda/': typeof AyudaIndexRoute
  '/recursos/': typeof RecursosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ayuda/profesionales/$id': typeof AyudaProfesionalesIdRoute
  '/ayuda/profesionales/': typeof AyudaProfesionalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca-de': typeof AcercaDeRoute
  '/cuenta': typeof CuentaRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/profesional/completar': typeof ProfesionalCompletarRoute
  '/profesional/login': typeof ProfesionalLoginRoute
  '/profesional/panel': typeof ProfesionalPanelRoute
  '/profesional/registro': typeof ProfesionalRegistroRoute
  '/recursos/enraizamiento': typeof RecursosEnraizamientoRoute
  '/recursos/primeros-auxilios': typeof RecursosPrimerosAuxiliosRoute
  '/recursos/reacciones-normales': typeof RecursosReaccionesNormalesRoute
  '/recursos/respirar': typeof RecursosRespirarRoute
  '/admin': typeof AdminIndexRoute
  '/ayuda': typeof AyudaIndexRoute
  '/recursos': typeof RecursosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ayuda/profesionales/$id': typeof AyudaProfesionalesIdRoute
  '/ayuda/profesionales': typeof AyudaProfesionalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acerca-de': typeof AcercaDeRoute
  '/cuenta': typeof CuentaRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/profesional/completar': typeof ProfesionalCompletarRoute
  '/profesional/login': typeof ProfesionalLoginRoute
  '/profesional/panel': typeof ProfesionalPanelRoute
  '/profesional/registro': typeof ProfesionalRegistroRoute
  '/recursos/enraizamiento': typeof RecursosEnraizamientoRoute
  '/recursos/primeros-auxilios': typeof RecursosPrimerosAuxiliosRoute
  '/recursos/reacciones-normales': typeof RecursosReaccionesNormalesRoute
  '/recursos/respirar': typeof RecursosRespirarRoute
  '/admin/': typeof AdminIndexRoute
  '/ayuda/': typeof AyudaIndexRoute
  '/recursos/': typeof RecursosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ayuda/profesionales/$id': typeof AyudaProfesionalesIdRoute
  '/ayuda/profesionales/': typeof AyudaProfesionalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerca-de'
    | '/cuenta'
    | '/signup'
    | '/social'
    | '/profesional/completar'
    | '/profesional/login'
    | '/profesional/panel'
    | '/profesional/registro'
    | '/recursos/enraizamiento'
    | '/recursos/primeros-auxilios'
    | '/recursos/reacciones-normales'
    | '/recursos/respirar'
    | '/admin/'
    | '/ayuda/'
    | '/recursos/'
    | '/api/auth/$'
    | '/ayuda/profesionales/$id'
    | '/ayuda/profesionales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acerca-de'
    | '/cuenta'
    | '/signup'
    | '/social'
    | '/profesional/completar'
    | '/profesional/login'
    | '/profesional/panel'
    | '/profesional/registro'
    | '/recursos/enraizamiento'
    | '/recursos/primeros-auxilios'
    | '/recursos/reacciones-normales'
    | '/recursos/respirar'
    | '/admin'
    | '/ayuda'
    | '/recursos'
    | '/api/auth/$'
    | '/ayuda/profesionales/$id'
    | '/ayuda/profesionales'
  id:
    | '__root__'
    | '/'
    | '/acerca-de'
    | '/cuenta'
    | '/signup'
    | '/social'
    | '/profesional/completar'
    | '/profesional/login'
    | '/profesional/panel'
    | '/profesional/registro'
    | '/recursos/enraizamiento'
    | '/recursos/primeros-auxilios'
    | '/recursos/reacciones-normales'
    | '/recursos/respirar'
    | '/admin/'
    | '/ayuda/'
    | '/recursos/'
    | '/api/auth/$'
    | '/ayuda/profesionales/$id'
    | '/ayuda/profesionales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcercaDeRoute: typeof AcercaDeRoute
  CuentaRoute: typeof CuentaRoute
  SignupRoute: typeof SignupRoute
  SocialRoute: typeof SocialRoute
  ProfesionalCompletarRoute: typeof ProfesionalCompletarRoute
  ProfesionalLoginRoute: typeof ProfesionalLoginRoute
  ProfesionalPanelRoute: typeof ProfesionalPanelRoute
  ProfesionalRegistroRoute: typeof ProfesionalRegistroRoute
  RecursosEnraizamientoRoute: typeof RecursosEnraizamientoRoute
  RecursosPrimerosAuxiliosRoute: typeof RecursosPrimerosAuxiliosRoute
  RecursosReaccionesNormalesRoute: typeof RecursosReaccionesNormalesRoute
  RecursosRespirarRoute: typeof RecursosRespirarRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AyudaIndexRoute: typeof AyudaIndexRoute
  RecursosIndexRoute: typeof RecursosIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AyudaProfesionalesIdRoute: typeof AyudaProfesionalesIdRoute
  AyudaProfesionalesIndexRoute: typeof AyudaProfesionalesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerca-de': {
      id: '/acerca-de'
      path: '/acerca-de'
      fullPath: '/acerca-de'
      preLoaderRoute: typeof AcercaDeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/': {
      id: '/recursos/'
      path: '/recursos'
      fullPath: '/recursos/'
      preLoaderRoute: typeof RecursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda/': {
      id: '/ayuda/'
      path: '/ayuda'
      fullPath: '/ayuda/'
      preLoaderRoute: typeof AyudaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/respirar': {
      id: '/recursos/respirar'
      path: '/recursos/respirar'
      fullPath: '/recursos/respirar'
      preLoaderRoute: typeof RecursosRespirarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/reacciones-normales': {
      id: '/recursos/reacciones-normales'
      path: '/recursos/reacciones-normales'
      fullPath: '/recursos/reacciones-normales'
      preLoaderRoute: typeof RecursosReaccionesNormalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/primeros-auxilios': {
      id: '/recursos/primeros-auxilios'
      path: '/recursos/primeros-auxilios'
      fullPath: '/recursos/primeros-auxilios'
      preLoaderRoute: typeof RecursosPrimerosAuxiliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/enraizamiento': {
      id: '/recursos/enraizamiento'
      path: '/recursos/enraizamiento'
      fullPath: '/recursos/enraizamiento'
      preLoaderRoute: typeof RecursosEnraizamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/registro': {
      id: '/profesional/registro'
      path: '/profesional/registro'
      fullPath: '/profesional/registro'
      preLoaderRoute: typeof ProfesionalRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/panel': {
      id: '/profesional/panel'
      path: '/profesional/panel'
      fullPath: '/profesional/panel'
      preLoaderRoute: typeof ProfesionalPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/login': {
      id: '/profesional/login'
      path: '/profesional/login'
      fullPath: '/profesional/login'
      preLoaderRoute: typeof ProfesionalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/completar': {
      id: '/profesional/completar'
      path: '/profesional/completar'
      fullPath: '/profesional/completar'
      preLoaderRoute: typeof ProfesionalCompletarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda/profesionales/': {
      id: '/ayuda/profesionales/'
      path: '/ayuda/profesionales'
      fullPath: '/ayuda/profesionales/'
      preLoaderRoute: typeof AyudaProfesionalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda/profesionales/$id': {
      id: '/ayuda/profesionales/$id'
      path: '/ayuda/profesionales/$id'
      fullPath: '/ayuda/profesionales/$id'
      preLoaderRoute: typeof AyudaProfesionalesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcercaDeRoute: AcercaDeRoute,
  CuentaRoute: CuentaRoute,
  SignupRoute: SignupRoute,
  SocialRoute: SocialRoute,
  ProfesionalCompletarRoute: ProfesionalCompletarRoute,
  ProfesionalLoginRoute: ProfesionalLoginRoute,
  ProfesionalPanelRoute: ProfesionalPanelRoute,
  ProfesionalRegistroRoute: ProfesionalRegistroRoute,
  RecursosEnraizamientoRoute: RecursosEnraizamientoRoute,
  RecursosPrimerosAuxiliosRoute: RecursosPrimerosAuxiliosRoute,
  RecursosReaccionesNormalesRoute: RecursosReaccionesNormalesRoute,
  RecursosRespirarRoute: RecursosRespirarRoute,
  AdminIndexRoute: AdminIndexRoute,
  AyudaIndexRoute: AyudaIndexRoute,
  RecursosIndexRoute: RecursosIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AyudaProfesionalesIdRoute: AyudaProfesionalesIdRoute,
  AyudaProfesionalesIndexRoute: AyudaProfesionalesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
