/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YaRouteImport } from './routes/ya'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PsicologosRouteImport } from './routes/psicologos'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AyudameRouteImport } from './routes/ayudame'
import { Route as AppRouteImport } from './routes/app'
import { Route as AcercaDeRouteImport } from './routes/acerca-de'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecursosIndexRouteImport } from './routes/recursos/index'
import { Route as AyudaIndexRouteImport } from './routes/ayuda/index'
import { Route as ApoyoIndexRouteImport } from './routes/apoyo/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RecursosRespirarRouteImport } from './routes/recursos/respirar'
import { Route as RecursosReaccionesNormalesRouteImport } from './routes/recursos/reacciones-normales'
import { Route as RecursosPrimerosAuxiliosRouteImport } from './routes/recursos/primeros-auxilios'
import { Route as RecursosEnraizamientoRouteImport } from './routes/recursos/enraizamiento'
import { Route as RecursosAutochequeoRouteImport } from './routes/recursos/autochequeo'
import { Route as ProfesionalSeguimientoRouteImport } from './routes/profesional/seguimiento'
import { Route as ProfesionalRegistroRouteImport } from './routes/profesional/registro'
import { Route as ProfesionalPresentacionRouteImport } from './routes/profesional/presentacion'
import { Route as ProfesionalPerfilRouteImport } from './routes/profesional/perfil'
import { Route as ProfesionalPanelRouteImport } from './routes/profesional/panel'
import { Route as ProfesionalLoginRouteImport } from './routes/profesional/login'
import { Route as ProfesionalDisponibilidadRouteImport } from './routes/profesional/disponibilidad'
import { Route as ProfesionalCompletarRouteImport } from './routes/profesional/completar'
import { Route as ProfesionalAudiosRouteImport } from './routes/profesional/audios'
import { Route as AyudaProfesionalesIndexRouteImport } from './routes/ayuda/profesionales/index'
import { Route as MediaDocumentSplatRouteImport } from './routes/media/document/$'
import { Route as MediaCertificateSplatRouteImport } from './routes/media/certificate/$'
import { Route as MediaAvatarSplatRouteImport } from './routes/media/avatar/$'
import { Route as MediaAudioSplatRouteImport } from './routes/media/audio/$'
import { Route as AyudaProfesionalesIdRouteImport } from './routes/ayuda/profesionales/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const YaRoute = YaRouteImport.update({
  id: '/ya',
  path: '/ya',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PsicologosRoute = PsicologosRouteImport.update({
  id: '/psicologos',
  path: '/psicologos',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudameRoute = AyudameRouteImport.update({
  id: '/ayudame',
  path: '/ayudame',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcercaDeRoute = AcercaDeRouteImport.update({
  id: '/acerca-de',
  path: '/acerca-de',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosIndexRoute = RecursosIndexRouteImport.update({
  id: '/recursos/',
  path: '/recursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaIndexRoute = AyudaIndexRouteImport.update({
  id: '/ayuda/',
  path: '/ayuda/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoyoIndexRoute = ApoyoIndexRouteImport.update({
  id: '/apoyo/',
  path: '/apoyo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRespirarRoute = RecursosRespirarRouteImport.update({
  id: '/recursos/respirar',
  path: '/recursos/respirar',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosReaccionesNormalesRoute =
  RecursosReaccionesNormalesRouteImport.update({
    id: '/recursos/reacciones-normales',
    path: '/recursos/reacciones-normales',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecursosPrimerosAuxiliosRoute =
  RecursosPrimerosAuxiliosRouteImport.update({
    id: '/recursos/primeros-auxilios',
    path: '/recursos/primeros-auxilios',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecursosEnraizamientoRoute = RecursosEnraizamientoRouteImport.update({
  id: '/recursos/enraizamiento',
  path: '/recursos/enraizamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosAutochequeoRoute = RecursosAutochequeoRouteImport.update({
  id: '/recursos/autochequeo',
  path: '/recursos/autochequeo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalSeguimientoRoute = ProfesionalSeguimientoRouteImport.update({
  id: '/profesional/seguimiento',
  path: '/profesional/seguimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalRegistroRoute = ProfesionalRegistroRouteImport.update({
  id: '/profesional/registro',
  path: '/profesional/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalPresentacionRoute = ProfesionalPresentacionRouteImport.update({
  id: '/profesional/presentacion',
  path: '/profesional/presentacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalPerfilRoute = ProfesionalPerfilRouteImport.update({
  id: '/profesional/perfil',
  path: '/profesional/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalPanelRoute = ProfesionalPanelRouteImport.update({
  id: '/profesional/panel',
  path: '/profesional/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalLoginRoute = ProfesionalLoginRouteImport.update({
  id: '/profesional/login',
  path: '/profesional/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalDisponibilidadRoute =
  ProfesionalDisponibilidadRouteImport.update({
    id: '/profesional/disponibilidad',
    path: '/profesional/disponibilidad',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfesionalCompletarRoute = ProfesionalCompletarRouteImport.update({
  id: '/profesional/completar',
  path: '/profesional/completar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalAudiosRoute = ProfesionalAudiosRouteImport.update({
  id: '/profesional/audios',
  path: '/profesional/audios',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaProfesionalesIndexRoute = AyudaProfesionalesIndexRouteImport.update({
  id: '/ayuda/profesionales/',
  path: '/ayuda/profesionales/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaDocumentSplatRoute = MediaDocumentSplatRouteImport.update({
  id: '/media/document/$',
  path: '/media/document/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaCertificateSplatRoute = MediaCertificateSplatRouteImport.update({
  id: '/media/certificate/$',
  path: '/media/certificate/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaAvatarSplatRoute = MediaAvatarSplatRouteImport.update({
  id: '/media/avatar/$',
  path: '/media/avatar/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaAudioSplatRoute = MediaAudioSplatRouteImport.update({
  id: '/media/audio/$',
  path: '/media/audio/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaProfesionalesIdRoute = AyudaProfesionalesIdRouteImport.update({
  id: '/ayuda/profesionales/$id',
  path: '/ayuda/profesionales/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca-de': typeof AcercaDeRoute
  '/app': typeof AppRoute
  '/ayudame': typeof AyudameRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/cuenta': typeof CuentaRoute
  '/psicologos': typeof PsicologosRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/terminos': typeof TerminosRoute
  '/ya': typeof YaRoute
  '/profesional/audios': typeof ProfesionalAudiosRoute
  '/profesional/completar': typeof ProfesionalCompletarRoute
  '/profesional/disponibilidad': typeof ProfesionalDisponibilidadRoute
  '/profesional/login': typeof ProfesionalLoginRoute
  '/profesional/panel': typeof ProfesionalPanelRoute
  '/profesional/perfil': typeof ProfesionalPerfilRoute
  '/profesional/presentacion': typeof ProfesionalPresentacionRoute
  '/profesional/registro': typeof ProfesionalRegistroRoute
  '/profesional/seguimiento': typeof ProfesionalSeguimientoRoute
  '/recursos/autochequeo': typeof RecursosAutochequeoRoute
  '/recursos/enraizamiento': typeof RecursosEnraizamientoRoute
  '/recursos/primeros-auxilios': typeof RecursosPrimerosAuxiliosRoute
  '/recursos/reacciones-normales': typeof RecursosReaccionesNormalesRoute
  '/recursos/respirar': typeof RecursosRespirarRoute
  '/admin/': typeof AdminIndexRoute
  '/apoyo/': typeof ApoyoIndexRoute
  '/ayuda/': typeof AyudaIndexRoute
  '/recursos/': typeof RecursosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ayuda/profesionales/$id': typeof AyudaProfesionalesIdRoute
  '/media/audio/$': typeof MediaAudioSplatRoute
  '/media/avatar/$': typeof MediaAvatarSplatRoute
  '/media/certificate/$': typeof MediaCertificateSplatRoute
  '/media/document/$': typeof MediaDocumentSplatRoute
  '/ayuda/profesionales/': typeof AyudaProfesionalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca-de': typeof AcercaDeRoute
  '/app': typeof AppRoute
  '/ayudame': typeof AyudameRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/cuenta': typeof CuentaRoute
  '/psicologos': typeof PsicologosRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/terminos': typeof TerminosRoute
  '/ya': typeof YaRoute
  '/profesional/audios': typeof ProfesionalAudiosRoute
  '/profesional/completar': typeof ProfesionalCompletarRoute
  '/profesional/disponibilidad': typeof ProfesionalDisponibilidadRoute
  '/profesional/login': typeof ProfesionalLoginRoute
  '/profesional/panel': typeof ProfesionalPanelRoute
  '/profesional/perfil': typeof ProfesionalPerfilRoute
  '/profesional/presentacion': typeof ProfesionalPresentacionRoute
  '/profesional/registro': typeof ProfesionalRegistroRoute
  '/profesional/seguimiento': typeof ProfesionalSeguimientoRoute
  '/recursos/autochequeo': typeof RecursosAutochequeoRoute
  '/recursos/enraizamiento': typeof RecursosEnraizamientoRoute
  '/recursos/primeros-auxilios': typeof RecursosPrimerosAuxiliosRoute
  '/recursos/reacciones-normales': typeof RecursosReaccionesNormalesRoute
  '/recursos/respirar': typeof RecursosRespirarRoute
  '/admin': typeof AdminIndexRoute
  '/apoyo': typeof ApoyoIndexRoute
  '/ayuda': typeof AyudaIndexRoute
  '/recursos': typeof RecursosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ayuda/profesionales/$id': typeof AyudaProfesionalesIdRoute
  '/media/audio/$': typeof MediaAudioSplatRoute
  '/media/avatar/$': typeof MediaAvatarSplatRoute
  '/media/certificate/$': typeof MediaCertificateSplatRoute
  '/media/document/$': typeof MediaDocumentSplatRoute
  '/ayuda/profesionales': typeof AyudaProfesionalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acerca-de': typeof AcercaDeRoute
  '/app': typeof AppRoute
  '/ayudame': typeof AyudameRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/cuenta': typeof CuentaRoute
  '/psicologos': typeof PsicologosRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/terminos': typeof TerminosRoute
  '/ya': typeof YaRoute
  '/profesional/audios': typeof ProfesionalAudiosRoute
  '/profesional/completar': typeof ProfesionalCompletarRoute
  '/profesional/disponibilidad': typeof ProfesionalDisponibilidadRoute
  '/profesional/login': typeof ProfesionalLoginRoute
  '/profesional/panel': typeof ProfesionalPanelRoute
  '/profesional/perfil': typeof ProfesionalPerfilRoute
  '/profesional/presentacion': typeof ProfesionalPresentacionRoute
  '/profesional/registro': typeof ProfesionalRegistroRoute
  '/profesional/seguimiento': typeof ProfesionalSeguimientoRoute
  '/recursos/autochequeo': typeof RecursosAutochequeoRoute
  '/recursos/enraizamiento': typeof RecursosEnraizamientoRoute
  '/recursos/primeros-auxilios': typeof RecursosPrimerosAuxiliosRoute
  '/recursos/reacciones-normales': typeof RecursosReaccionesNormalesRoute
  '/recursos/respirar': typeof RecursosRespirarRoute
  '/admin/': typeof AdminIndexRoute
  '/apoyo/': typeof ApoyoIndexRoute
  '/ayuda/': typeof AyudaIndexRoute
  '/recursos/': typeof RecursosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ayuda/profesionales/$id': typeof AyudaProfesionalesIdRoute
  '/media/audio/$': typeof MediaAudioSplatRoute
  '/media/avatar/$': typeof MediaAvatarSplatRoute
  '/media/certificate/$': typeof MediaCertificateSplatRoute
  '/media/document/$': typeof MediaDocumentSplatRoute
  '/ayuda/profesionales/': typeof AyudaProfesionalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerca-de'
    | '/app'
    | '/ayudame'
    | '/como-funciona'
    | '/cuenta'
    | '/psicologos'
    | '/signup'
    | '/social'
    | '/terminos'
    | '/ya'
    | '/profesional/audios'
    | '/profesional/completar'
    | '/profesional/disponibilidad'
    | '/profesional/login'
    | '/profesional/panel'
    | '/profesional/perfil'
    | '/profesional/presentacion'
    | '/profesional/registro'
    | '/profesional/seguimiento'
    | '/recursos/autochequeo'
    | '/recursos/enraizamiento'
    | '/recursos/primeros-auxilios'
    | '/recursos/reacciones-normales'
    | '/recursos/respirar'
    | '/admin/'
    | '/apoyo/'
    | '/ayuda/'
    | '/recursos/'
    | '/api/auth/$'
    | '/ayuda/profesionales/$id'
    | '/media/audio/$'
    | '/media/avatar/$'
    | '/media/certificate/$'
    | '/media/document/$'
    | '/ayuda/profesionales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acerca-de'
    | '/app'
    | '/ayudame'
    | '/como-funciona'
    | '/cuenta'
    | '/psicologos'
    | '/signup'
    | '/social'
    | '/terminos'
    | '/ya'
    | '/profesional/audios'
    | '/profesional/completar'
    | '/profesional/disponibilidad'
    | '/profesional/login'
    | '/profesional/panel'
    | '/profesional/perfil'
    | '/profesional/presentacion'
    | '/profesional/registro'
    | '/profesional/seguimiento'
    | '/recursos/autochequeo'
    | '/recursos/enraizamiento'
    | '/recursos/primeros-auxilios'
    | '/recursos/reacciones-normales'
    | '/recursos/respirar'
    | '/admin'
    | '/apoyo'
    | '/ayuda'
    | '/recursos'
    | '/api/auth/$'
    | '/ayuda/profesionales/$id'
    | '/media/audio/$'
    | '/media/avatar/$'
    | '/media/certificate/$'
    | '/media/document/$'
    | '/ayuda/profesionales'
  id:
    | '__root__'
    | '/'
    | '/acerca-de'
    | '/app'
    | '/ayudame'
    | '/como-funciona'
    | '/cuenta'
    | '/psicologos'
    | '/signup'
    | '/social'
    | '/terminos'
    | '/ya'
    | '/profesional/audios'
    | '/profesional/completar'
    | '/profesional/disponibilidad'
    | '/profesional/login'
    | '/profesional/panel'
    | '/profesional/perfil'
    | '/profesional/presentacion'
    | '/profesional/registro'
    | '/profesional/seguimiento'
    | '/recursos/autochequeo'
    | '/recursos/enraizamiento'
    | '/recursos/primeros-auxilios'
    | '/recursos/reacciones-normales'
    | '/recursos/respirar'
    | '/admin/'
    | '/apoyo/'
    | '/ayuda/'
    | '/recursos/'
    | '/api/auth/$'
    | '/ayuda/profesionales/$id'
    | '/media/audio/$'
    | '/media/avatar/$'
    | '/media/certificate/$'
    | '/media/document/$'
    | '/ayuda/profesionales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcercaDeRoute: typeof AcercaDeRoute
  AppRoute: typeof AppRoute
  AyudameRoute: typeof AyudameRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  CuentaRoute: typeof CuentaRoute
  PsicologosRoute: typeof PsicologosRoute
  SignupRoute: typeof SignupRoute
  SocialRoute: typeof SocialRoute
  TerminosRoute: typeof TerminosRoute
  YaRoute: typeof YaRoute
  ProfesionalAudiosRoute: typeof ProfesionalAudiosRoute
  ProfesionalCompletarRoute: typeof ProfesionalCompletarRoute
  ProfesionalDisponibilidadRoute: typeof ProfesionalDisponibilidadRoute
  ProfesionalLoginRoute: typeof ProfesionalLoginRoute
  ProfesionalPanelRoute: typeof ProfesionalPanelRoute
  ProfesionalPerfilRoute: typeof ProfesionalPerfilRoute
  ProfesionalPresentacionRoute: typeof ProfesionalPresentacionRoute
  ProfesionalRegistroRoute: typeof ProfesionalRegistroRoute
  ProfesionalSeguimientoRoute: typeof ProfesionalSeguimientoRoute
  RecursosAutochequeoRoute: typeof RecursosAutochequeoRoute
  RecursosEnraizamientoRoute: typeof RecursosEnraizamientoRoute
  RecursosPrimerosAuxiliosRoute: typeof RecursosPrimerosAuxiliosRoute
  RecursosReaccionesNormalesRoute: typeof RecursosReaccionesNormalesRoute
  RecursosRespirarRoute: typeof RecursosRespirarRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApoyoIndexRoute: typeof ApoyoIndexRoute
  AyudaIndexRoute: typeof AyudaIndexRoute
  RecursosIndexRoute: typeof RecursosIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AyudaProfesionalesIdRoute: typeof AyudaProfesionalesIdRoute
  MediaAudioSplatRoute: typeof MediaAudioSplatRoute
  MediaAvatarSplatRoute: typeof MediaAvatarSplatRoute
  MediaCertificateSplatRoute: typeof MediaCertificateSplatRoute
  MediaDocumentSplatRoute: typeof MediaDocumentSplatRoute
  AyudaProfesionalesIndexRoute: typeof AyudaProfesionalesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ya': {
      id: '/ya'
      path: '/ya'
      fullPath: '/ya'
      preLoaderRoute: typeof YaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psicologos': {
      id: '/psicologos'
      path: '/psicologos'
      fullPath: '/psicologos'
      preLoaderRoute: typeof PsicologosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayudame': {
      id: '/ayudame'
      path: '/ayudame'
      fullPath: '/ayudame'
      preLoaderRoute: typeof AyudameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerca-de': {
      id: '/acerca-de'
      path: '/acerca-de'
      fullPath: '/acerca-de'
      preLoaderRoute: typeof AcercaDeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/': {
      id: '/recursos/'
      path: '/recursos'
      fullPath: '/recursos/'
      preLoaderRoute: typeof RecursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda/': {
      id: '/ayuda/'
      path: '/ayuda'
      fullPath: '/ayuda/'
      preLoaderRoute: typeof AyudaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoyo/': {
      id: '/apoyo/'
      path: '/apoyo'
      fullPath: '/apoyo/'
      preLoaderRoute: typeof ApoyoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/respirar': {
      id: '/recursos/respirar'
      path: '/recursos/respirar'
      fullPath: '/recursos/respirar'
      preLoaderRoute: typeof RecursosRespirarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/reacciones-normales': {
      id: '/recursos/reacciones-normales'
      path: '/recursos/reacciones-normales'
      fullPath: '/recursos/reacciones-normales'
      preLoaderRoute: typeof RecursosReaccionesNormalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/primeros-auxilios': {
      id: '/recursos/primeros-auxilios'
      path: '/recursos/primeros-auxilios'
      fullPath: '/recursos/primeros-auxilios'
      preLoaderRoute: typeof RecursosPrimerosAuxiliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/enraizamiento': {
      id: '/recursos/enraizamiento'
      path: '/recursos/enraizamiento'
      fullPath: '/recursos/enraizamiento'
      preLoaderRoute: typeof RecursosEnraizamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/autochequeo': {
      id: '/recursos/autochequeo'
      path: '/recursos/autochequeo'
      fullPath: '/recursos/autochequeo'
      preLoaderRoute: typeof RecursosAutochequeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/seguimiento': {
      id: '/profesional/seguimiento'
      path: '/profesional/seguimiento'
      fullPath: '/profesional/seguimiento'
      preLoaderRoute: typeof ProfesionalSeguimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/registro': {
      id: '/profesional/registro'
      path: '/profesional/registro'
      fullPath: '/profesional/registro'
      preLoaderRoute: typeof ProfesionalRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/presentacion': {
      id: '/profesional/presentacion'
      path: '/profesional/presentacion'
      fullPath: '/profesional/presentacion'
      preLoaderRoute: typeof ProfesionalPresentacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/perfil': {
      id: '/profesional/perfil'
      path: '/profesional/perfil'
      fullPath: '/profesional/perfil'
      preLoaderRoute: typeof ProfesionalPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/panel': {
      id: '/profesional/panel'
      path: '/profesional/panel'
      fullPath: '/profesional/panel'
      preLoaderRoute: typeof ProfesionalPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/login': {
      id: '/profesional/login'
      path: '/profesional/login'
      fullPath: '/profesional/login'
      preLoaderRoute: typeof ProfesionalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/disponibilidad': {
      id: '/profesional/disponibilidad'
      path: '/profesional/disponibilidad'
      fullPath: '/profesional/disponibilidad'
      preLoaderRoute: typeof ProfesionalDisponibilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/completar': {
      id: '/profesional/completar'
      path: '/profesional/completar'
      fullPath: '/profesional/completar'
      preLoaderRoute: typeof ProfesionalCompletarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/audios': {
      id: '/profesional/audios'
      path: '/profesional/audios'
      fullPath: '/profesional/audios'
      preLoaderRoute: typeof ProfesionalAudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda/profesionales/': {
      id: '/ayuda/profesionales/'
      path: '/ayuda/profesionales'
      fullPath: '/ayuda/profesionales/'
      preLoaderRoute: typeof AyudaProfesionalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/document/$': {
      id: '/media/document/$'
      path: '/media/document/$'
      fullPath: '/media/document/$'
      preLoaderRoute: typeof MediaDocumentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/certificate/$': {
      id: '/media/certificate/$'
      path: '/media/certificate/$'
      fullPath: '/media/certificate/$'
      preLoaderRoute: typeof MediaCertificateSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/avatar/$': {
      id: '/media/avatar/$'
      path: '/media/avatar/$'
      fullPath: '/media/avatar/$'
      preLoaderRoute: typeof MediaAvatarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/audio/$': {
      id: '/media/audio/$'
      path: '/media/audio/$'
      fullPath: '/media/audio/$'
      preLoaderRoute: typeof MediaAudioSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda/profesionales/$id': {
      id: '/ayuda/profesionales/$id'
      path: '/ayuda/profesionales/$id'
      fullPath: '/ayuda/profesionales/$id'
      preLoaderRoute: typeof AyudaProfesionalesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcercaDeRoute: AcercaDeRoute,
  AppRoute: AppRoute,
  AyudameRoute: AyudameRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  CuentaRoute: CuentaRoute,
  PsicologosRoute: PsicologosRoute,
  SignupRoute: SignupRoute,
  SocialRoute: SocialRoute,
  TerminosRoute: TerminosRoute,
  YaRoute: YaRoute,
  ProfesionalAudiosRoute: ProfesionalAudiosRoute,
  ProfesionalCompletarRoute: ProfesionalCompletarRoute,
  ProfesionalDisponibilidadRoute: ProfesionalDisponibilidadRoute,
  ProfesionalLoginRoute: ProfesionalLoginRoute,
  ProfesionalPanelRoute: ProfesionalPanelRoute,
  ProfesionalPerfilRoute: ProfesionalPerfilRoute,
  ProfesionalPresentacionRoute: ProfesionalPresentacionRoute,
  ProfesionalRegistroRoute: ProfesionalRegistroRoute,
  ProfesionalSeguimientoRoute: ProfesionalSeguimientoRoute,
  RecursosAutochequeoRoute: RecursosAutochequeoRoute,
  RecursosEnraizamientoRoute: RecursosEnraizamientoRoute,
  RecursosPrimerosAuxiliosRoute: RecursosPrimerosAuxiliosRoute,
  RecursosReaccionesNormalesRoute: RecursosReaccionesNormalesRoute,
  RecursosRespirarRoute: RecursosRespirarRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApoyoIndexRoute: ApoyoIndexRoute,
  AyudaIndexRoute: AyudaIndexRoute,
  RecursosIndexRoute: RecursosIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AyudaProfesionalesIdRoute: AyudaProfesionalesIdRoute,
  MediaAudioSplatRoute: MediaAudioSplatRoute,
  MediaAvatarSplatRoute: MediaAvatarSplatRoute,
  MediaCertificateSplatRoute: MediaCertificateSplatRoute,
  MediaDocumentSplatRoute: MediaDocumentSplatRoute,
  AyudaProfesionalesIndexRoute: AyudaProfesionalesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
